from pyautocad import Autocad, APoint

draw_info=[['节点', 1.0, 5.0, 3.0, 7.0, 9.0, 11.0, 13.0, 15.0, 17.0, 19.0, 81.0, 55.0, 71.0, 22.0, 186.0, 41.0, 69.0, 83.0, 21.0, 187.0, 57.0, 73.0, 59.0, 75.0, 61.0, 77.0, 63.0, 79.0, 100.0, 103.0, 185.0, 193.0, 176.0, 177.0, 191.0, 178.0, 179.0, 180.0, 181.0, 5], ['F1max', 38.71, -38.71, -33.23, 27.32, 25.87, -21.61, -16.92, 12.91, 16.77, -12.11, 6.97, 8.78, -4.92, -18.03, 3.31, 10.91, 30.94, 1.05, -20.26, 0.79, 25.08, -0.8, -13.96, 1.01, -3.99, 0.55, -6.16, -0.69, -9.37, -0.87, 0.1, 0.04, -30.92, 24.24, 0.04, 0.11, 0.14, 0.19, -0.25, 6], ['F2max', 8.7, 8.54, -19.1, -18.18, 16.03, 14.22, -5.76, -5.62, -16.03, -14.29, 3.56, -51.35, 3.56, -55.65, 3.01, -12.99, 22.87, -21.92, -52.62, 3.13, -88.01, 3.08, -73.58, 2.8, -62.03, 2.89, -30.03, 3.16, -2.98, 4.82, 40.44, 19.7, -0.04, 0.06, 26.25, 43.88, 8.08, 7.72, 7.88, 6], ['F3max', 251.51, 273.65, 304.89, 311.3, 52.47, 55.07, 216.01, 209.66, 50.78, 60.28, 46.51, 10.1, 140.58, 67.85, 133.48, 49.02, 63.15, 19.63, 69.67, 93.28, 63.01, 212.49, 83.08, 128.14, 63.45, 148.08, 13.65, 98.12, 2.3, 23.18, 1.07, 1.0, 2.38, 1.31, 1.0, 1.86, 2.04, 2.05, 1.65, 6], ['M1max', -144.25, -143.37, 50.68, 47.68, -53.07, -45.83, 10.9, 10.45, 53.18, 46.04, -4.31, 38.22, -4.35, -34.28, -3.12, 11.96, -13.71, 12.1, 29.5, -3.38, 83.59, -3.31, 69.82, -2.63, 58.79, -2.84, 22.15, -3.42, 1.72, 22.28, 1.05, 0.0, 0.0, 0.0, 0.0, 1.8, 1.77, 1.92, 1.35, 7], ['M2max', 145.83, -145.86, -121.2, 112.48, 98.53, -92.29, -55.63, 50.89, 55.99, -47.99, 13.22, -6.06, -7.54, 3.0, 3.82, -6.43, -25.66, 0.95, -5.79, 1.7, -8.89, -1.58, 4.43, 2.12, 4.28, 1.8, 5.9, -2.77, -0.01, 0.0, 0.0, 0.0, 1.89, -1.07, 0.0, 0.0, 0.0, 0.0, 0.0, 7], ['M3max', 8.73, 8.74, -0.16, 0.13, 0.02, 0.01, 0.04, 0.04, 0.03, 0.01, 0.0, -0.04, 0.0, 0.14, 0.0, -0.07, 0.01, 0.04, 0.14, 0.0, -0.16, 0.0, 0.18, 0.0, 0.07, 0.0, 0.1, 0.0, 4.96, 0.73, 0.11, 0.0, -0.03, 0.05, 0.0, -0.12, -0.16, -0.23, 0.4, 5], ['埋件尺寸', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 4], ['备注', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 2]]
def draw_cad(draw_info=None):
    draw_info=draw_info
    acad = Autocad(create_if_not_exists=True)
    acad.ActiveDocument.ActiveTextStyle.SetFont("楷体", False, False, 1, 0 or 0)
    x_wenzi=[0]
    x_line=[0]
    for i in range(len(draw_info)):
        #先确定横坐标
        width=draw_info[i][-1]
        zuobiao_x=x_wenzi[i]+width*4
        x_wenzi.append(zuobiao_x)
        if i==0:
            x_line[0]=x_line[0]-width*2
        x_line.append(zuobiao_x-width*2)
    zongchang=x_wenzi.pop(-1)
    for i in range(len(draw_info)):
        content=draw_info[i][:-1]
        for j in range(len(content)):
            p1=APoint(x_wenzi[i],0-j*5)
            textObj=acad.model.addText(str(content[j]),p1,2.5)
            AlignNum = 4
            textObj.Alignment = AlignNum
            textObj.TextAlignmentPoint =p1
    col=len(draw_info)
    row=len(draw_info[0])
    for i in range(col):
        p1=APoint(x_line[i],2.5)
        p2=APoint(x_line[i],2.5-(row-1)*5)
        acad.model.addLine(p1,p2)
    p1=APoint(x_line[-1]+5,2.5)
    p2=APoint(x_line[-1]+5,2.5-(row-1)*5)
    acad.model.addLine(p1, p2)
    for i in range(row):
        p1=APoint(-10,2.5-i*5)
        p2=APoint(-10+zongchang+11,2.5-i*5)
        acad.model.addLine(p1, p2)






draw_cad(draw_info=draw_info)